
export const villas = [
  {
    id: 1,
    name: "Taj Hotel",
    location: "Mumbai",
    category: "Mountains",
    guests: 10,
    bedrooms: 6,
    bathrooms: 10,
    squareMeter: "400",
    rating: 4.7,
    image: "/villa1.jpg",
    dailyRent: "240",
  },
  {
    id: 2,
    name: "Blue Side Hotel",
    location: "Pune",
    category: "Mountains",
    guests: 8,
    bedrooms: 8,
    bathrooms: 12,
    squareMeter: "450",
    rating: 4.4,
    image: "/villa2.jpg",
    dailyRent: "300",
  },
  {
    id: 3,
    name: "Rajlaxmi Hotel",
    location: "Vasi",
    category: "Seaside",
    guests: 12,
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "500",
    rating: 4.9,
    image: "/villa3.jpg",
    dailyRent: "200",
  },
  {
    id: 4,
    name: "Mamta Hotel",
    location: "Ahmedabad",
    category: "Mountains",
    guests: 12,
    bedrooms: 15,
    bathrooms: 20,
    squareMeter: "750",
    rating: 5.0,
    image: "/villa4.jpg",
    dailyRent: "260",
  },
  {
    id: 5,
    name: "Ornate",
    location: "Vadodara",
    category: "Mountains",
    guests: 4,
    bedrooms: 5,
    bathrooms: 6,
    squareMeter: "275",
    rating: 4.0,
    image: "/villa5.jpg",
    dailyRent: "200",
  },
  {
    id: 6,
    name: "The Leela Palace",
    location: "Jaipur",
    category: "Mountains",
    guests: 12,
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "500",
    rating: 4.9,
    image: "/villa6.jpg",
    dailyRent: "320",
  },
  {
    id: 7,
    name: "The Ritz-Carlton",
    location: "Bangalore",
    category: "Mountains",
    guests: 15,
    bedrooms: 8,
    bathrooms: 10,
    squareMeter: "1000",
    rating: 4.8,
    image: "/villa7.jpg",
    dailyRent: "280",
  },
  {
    id: 8,
    name: "Oberoi Amarvilas",
    location: "koimbatore",
    category: "Seaside",
    guests: 25,
    bedrooms: 25,
    bathrooms: 25,
    squareMeter: "1500",
    rating: 5.0,
    image: "/villa8.jpg",
    dailyRent: "400",
  },
  {
    id: 9,
    name: "JW Marriott ",
    location: "Mumbai",
    category: "Seaside",
    guests: 5,
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "240",
    rating: 3.8,
    image: "/villa9.jpg",
    dailyRent: "180",
  },
  {
    id: 10,
    name: "Crystal Waters Hotel",
    location: "kolkata",
    category: "Seaside",
    guests: 15,
    bedrooms: 9,
    bathrooms: 9,
    squareMeter: "340",
    rating: 3.9,
    image: "/villa12.jpg",
    dailyRent: "280",
  },
  {
    id: 11,
    name: "Regal Heights Resort",
    location: "Shimla",
    category: "Mountains",
    guests: 25,
    bedrooms: 20,
    bathrooms: 17,
    squareMeter: "600",
    rating: 4.9,
    image: "/villa11.jpg",
    dailyRent: "400",
  },
  {
    id: 12,
    name: "Majestic Peaks Lodge",
    location: "Himadri",
    category: "Mountains",
    guests: 30,
    bedrooms: 25,
    bathrooms: 25,
    squareMeter: "900",
    rating: 4.9,
    image: "/villa10.jpg",
    dailyRent: "300",
  },

];

